// Define a type for the team image map
type TeamImageMap = {
  [key: string]: string;
};

// Create the team image map
const teamImageMap: TeamImageMap = {
  Arsenal: "/team-images/arsenal.png",
  "Aston Villa": "/team-images/aston-villa.png",
  "AFC Bournemouth": "/team-images/afc-bournemouth.png",
  Brentford: "/team-images/brentford.png",
  "Brighton & Hove Albion": "/team-images/brighton-&-hove-albion.png",
  Chelsea: "/team-images/chelsea.png",
  "Crystal Palace": "/team-images/crystal-palace.png",
  Everton: "/team-images/everton.png",
  Fulham: "/team-images/fulham.png",
  Liverpool: "/team-images/liverpool.png",
  "Manchester City": "/team-images/manchester-city.png",
  "Manchester United": "/team-images/manchester-united.png",
  "Newcastle United": "/team-images/newcastle-united.png",
  "Nottingham Forest": "/team-images/nottingham-forest.png",
  "Tottenham Hotspur": "/team-images/tottenham-hotspur.png",
  "West Ham United": "/team-images/west-ham-united.png",
  "Wolverhampton Wanderers": "/team-images/wolverhampton-wanderers.png",
  "Ipswich Town": "/team-images/ipswich.png",
  Southampton: "/team-images/southampton.png",
  "Leicester City": "/team-images/leicester.png",
  "Birmingham City": "/team-images/birmingham-city.png",
  "Wycombe Wanderers": "/team-images/wycombe-wanerers.png",
  "Wrexham": "/team-images/wrexham.png",
  "Huddersfield Town": "/team-images/huddersfield-town.png",
  "Barnsley": "/team-images/barnsley.png",
  Reading: "/team-images/reading.png",
  "Stockport County": "/team-images/stockport-county.png",
  "Leyton Orient": "/team-images/leyton-orient.png",
  "Mansfield Town": "/team-images/mansfield-town.png",
  "Bolton Wanderers": "/team-images/bolton-wanderers.png",
  "Charlton Athletic": "/team-images/charlton-athletic.png",
  "Lincoln City": "/team-images/lincoln-city.png",
  Stevenage: "/team-images/stevenage.png",
  "Exeter City": "/team-images/exeter-city.png",
  Blackpool: "/team-images/blackpool.png",
  "Rotherham United": "/team-images/rotherham-united.png",
  "Wigan Athletic": "/team-images/wigan-athletic.png",
  "Northampton Town": "/team-images/northampton-town.png",
  "Peterborough United": "/team-images/peterborough-united.png",
  "Bristol Rovers": "/team-images/bristol-rovers.png",
  "Crawlerley Town": "/team-images/crawlerley-town.png",
  "Shrewsbury Town": "/team-images/shrewsbury-town.png",
  "Cambridge United": "/team-images/cambridge-united.png",
  "Burton Albion": "/team-images/burton-albion.png",
  Leeds: "/team-images/leeds.png",
  Burnley: "/team-images/burnley.png",
  "Sheffield United": "/team-images/sheffield-united.png",
  Sunderland: "/team-images/sunderland.png",
  Middlesbrough: "/team-images/middlesbrough.png",
  "West Bromwich Albion": "/team-images/west-bromwich-albion.png",
  "Blackburn Rovers": "/team-images/blackburn-rovers.png",
  "Bristol City": "/team-images/bristol-city.png",
  Watford: "/team-images/watford.png",
  "Sheffield Wednesday": "/team-images/sheffield-wednesday.png",
  "Norwich City": "/team-images/norwich-city.png",
  "Swansea City": "/team-images/swansea-city.png",
  Millwall: "/team-images/millwall.png",
  "Preston North End": "/team-images/preston-north-end.png",
  "Coventry City": "/team-images/coventry-city.png",
  "Queens Park Rangers": "/team-images/queens-park-rangers.png",
  "Oxford United": "/team-images/oxford-united.png",
  "Derby County": "/team-images/derby-county.png",
  "Stoke City": "/team-images/stoke-city.png",
  "Luton Town": "/team-images/luton-town.png",
  Portsmouth: "/team-images/portsmouth.png",
  "Hull City": "/team-images/hull-city.png",
  "Cardiff City": "/team-images/cardiff-city.png",
  "Plymouth Argyle": "/team-images/plymouth-argyle.png",
};

// Define the function to get the team image
export const getTeamImage = (teamName: string): string => {
  return teamImageMap[teamName] || "/team-images/default.png";
};
